/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TalentPoolRouteImport } from './routes/talent-pool'
import { Route as SkillGapRouteImport } from './routes/skill-gap'
import { Route as ShortlistRouteImport } from './routes/shortlist'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SchedulerRouteImport } from './routes/scheduler'
import { Route as SavedJobsRouteImport } from './routes/saved-jobs'
import { Route as ResumeRewriterRouteImport } from './routes/resume-rewriter'
import { Route as ResumeLibraryRouteImport } from './routes/resume-library'
import { Route as ResumeAnalyzerRouteImport } from './routes/resume-analyzer'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MockInterviewRouteImport } from './routes/mock-interview'
import { Route as LearningRouteImport } from './routes/learning'
import { Route as JobMatchesRouteImport } from './routes/job-matches'
import { Route as JdMatchingRouteImport } from './routes/jd-matching'
import { Route as InterviewPrepRouteImport } from './routes/interview-prep'
import { Route as HiringAnalyticsRouteImport } from './routes/hiring-analytics'
import { Route as CompareCandidatesRouteImport } from './routes/compare-candidates'
import { Route as CareerRoadmapRouteImport } from './routes/career-roadmap'
import { Route as CareerPredictionRouteImport } from './routes/career-prediction'
import { Route as CareerCoachRouteImport } from './routes/career-coach'
import { Route as BulkScreeningRouteImport } from './routes/bulk-screening'
import { Route as AtsScoreRouteImport } from './routes/ats-score'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'

const TalentPoolRoute = TalentPoolRouteImport.update({
  id: '/talent-pool',
  path: '/talent-pool',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillGapRoute = SkillGapRouteImport.update({
  id: '/skill-gap',
  path: '/skill-gap',
  getParentRoute: () => rootRouteImport,
} as any)
const ShortlistRoute = ShortlistRouteImport.update({
  id: '/shortlist',
  path: '/shortlist',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulerRoute = SchedulerRouteImport.update({
  id: '/scheduler',
  path: '/scheduler',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedJobsRoute = SavedJobsRouteImport.update({
  id: '/saved-jobs',
  path: '/saved-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeRewriterRoute = ResumeRewriterRouteImport.update({
  id: '/resume-rewriter',
  path: '/resume-rewriter',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeLibraryRoute = ResumeLibraryRouteImport.update({
  id: '/resume-library',
  path: '/resume-library',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeAnalyzerRoute = ResumeAnalyzerRouteImport.update({
  id: '/resume-analyzer',
  path: '/resume-analyzer',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MockInterviewRoute = MockInterviewRouteImport.update({
  id: '/mock-interview',
  path: '/mock-interview',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningRoute = LearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => rootRouteImport,
} as any)
const JobMatchesRoute = JobMatchesRouteImport.update({
  id: '/job-matches',
  path: '/job-matches',
  getParentRoute: () => rootRouteImport,
} as any)
const JdMatchingRoute = JdMatchingRouteImport.update({
  id: '/jd-matching',
  path: '/jd-matching',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewPrepRoute = InterviewPrepRouteImport.update({
  id: '/interview-prep',
  path: '/interview-prep',
  getParentRoute: () => rootRouteImport,
} as any)
const HiringAnalyticsRoute = HiringAnalyticsRouteImport.update({
  id: '/hiring-analytics',
  path: '/hiring-analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareCandidatesRoute = CompareCandidatesRouteImport.update({
  id: '/compare-candidates',
  path: '/compare-candidates',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerRoadmapRoute = CareerRoadmapRouteImport.update({
  id: '/career-roadmap',
  path: '/career-roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerPredictionRoute = CareerPredictionRouteImport.update({
  id: '/career-prediction',
  path: '/career-prediction',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerCoachRoute = CareerCoachRouteImport.update({
  id: '/career-coach',
  path: '/career-coach',
  getParentRoute: () => rootRouteImport,
} as any)
const BulkScreeningRoute = BulkScreeningRouteImport.update({
  id: '/bulk-screening',
  path: '/bulk-screening',
  getParentRoute: () => rootRouteImport,
} as any)
const AtsScoreRoute = AtsScoreRouteImport.update({
  id: '/ats-score',
  path: '/ats-score',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/ats-score': typeof AtsScoreRoute
  '/bulk-screening': typeof BulkScreeningRoute
  '/career-coach': typeof CareerCoachRoute
  '/career-prediction': typeof CareerPredictionRoute
  '/career-roadmap': typeof CareerRoadmapRoute
  '/compare-candidates': typeof CompareCandidatesRoute
  '/hiring-analytics': typeof HiringAnalyticsRoute
  '/interview-prep': typeof InterviewPrepRoute
  '/jd-matching': typeof JdMatchingRoute
  '/job-matches': typeof JobMatchesRoute
  '/learning': typeof LearningRoute
  '/mock-interview': typeof MockInterviewRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/resume-analyzer': typeof ResumeAnalyzerRoute
  '/resume-library': typeof ResumeLibraryRoute
  '/resume-rewriter': typeof ResumeRewriterRoute
  '/saved-jobs': typeof SavedJobsRoute
  '/scheduler': typeof SchedulerRoute
  '/settings': typeof SettingsRoute
  '/shortlist': typeof ShortlistRoute
  '/skill-gap': typeof SkillGapRoute
  '/talent-pool': typeof TalentPoolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/ats-score': typeof AtsScoreRoute
  '/bulk-screening': typeof BulkScreeningRoute
  '/career-coach': typeof CareerCoachRoute
  '/career-prediction': typeof CareerPredictionRoute
  '/career-roadmap': typeof CareerRoadmapRoute
  '/compare-candidates': typeof CompareCandidatesRoute
  '/hiring-analytics': typeof HiringAnalyticsRoute
  '/interview-prep': typeof InterviewPrepRoute
  '/jd-matching': typeof JdMatchingRoute
  '/job-matches': typeof JobMatchesRoute
  '/learning': typeof LearningRoute
  '/mock-interview': typeof MockInterviewRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/resume-analyzer': typeof ResumeAnalyzerRoute
  '/resume-library': typeof ResumeLibraryRoute
  '/resume-rewriter': typeof ResumeRewriterRoute
  '/saved-jobs': typeof SavedJobsRoute
  '/scheduler': typeof SchedulerRoute
  '/settings': typeof SettingsRoute
  '/shortlist': typeof ShortlistRoute
  '/skill-gap': typeof SkillGapRoute
  '/talent-pool': typeof TalentPoolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/ats-score': typeof AtsScoreRoute
  '/bulk-screening': typeof BulkScreeningRoute
  '/career-coach': typeof CareerCoachRoute
  '/career-prediction': typeof CareerPredictionRoute
  '/career-roadmap': typeof CareerRoadmapRoute
  '/compare-candidates': typeof CompareCandidatesRoute
  '/hiring-analytics': typeof HiringAnalyticsRoute
  '/interview-prep': typeof InterviewPrepRoute
  '/jd-matching': typeof JdMatchingRoute
  '/job-matches': typeof JobMatchesRoute
  '/learning': typeof LearningRoute
  '/mock-interview': typeof MockInterviewRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/resume-analyzer': typeof ResumeAnalyzerRoute
  '/resume-library': typeof ResumeLibraryRoute
  '/resume-rewriter': typeof ResumeRewriterRoute
  '/saved-jobs': typeof SavedJobsRoute
  '/scheduler': typeof SchedulerRoute
  '/settings': typeof SettingsRoute
  '/shortlist': typeof ShortlistRoute
  '/skill-gap': typeof SkillGapRoute
  '/talent-pool': typeof TalentPoolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/ats-score'
    | '/bulk-screening'
    | '/career-coach'
    | '/career-prediction'
    | '/career-roadmap'
    | '/compare-candidates'
    | '/hiring-analytics'
    | '/interview-prep'
    | '/jd-matching'
    | '/job-matches'
    | '/learning'
    | '/mock-interview'
    | '/notifications'
    | '/profile'
    | '/reports'
    | '/resume-analyzer'
    | '/resume-library'
    | '/resume-rewriter'
    | '/saved-jobs'
    | '/scheduler'
    | '/settings'
    | '/shortlist'
    | '/skill-gap'
    | '/talent-pool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/ats-score'
    | '/bulk-screening'
    | '/career-coach'
    | '/career-prediction'
    | '/career-roadmap'
    | '/compare-candidates'
    | '/hiring-analytics'
    | '/interview-prep'
    | '/jd-matching'
    | '/job-matches'
    | '/learning'
    | '/mock-interview'
    | '/notifications'
    | '/profile'
    | '/reports'
    | '/resume-analyzer'
    | '/resume-library'
    | '/resume-rewriter'
    | '/saved-jobs'
    | '/scheduler'
    | '/settings'
    | '/shortlist'
    | '/skill-gap'
    | '/talent-pool'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/ats-score'
    | '/bulk-screening'
    | '/career-coach'
    | '/career-prediction'
    | '/career-roadmap'
    | '/compare-candidates'
    | '/hiring-analytics'
    | '/interview-prep'
    | '/jd-matching'
    | '/job-matches'
    | '/learning'
    | '/mock-interview'
    | '/notifications'
    | '/profile'
    | '/reports'
    | '/resume-analyzer'
    | '/resume-library'
    | '/resume-rewriter'
    | '/saved-jobs'
    | '/scheduler'
    | '/settings'
    | '/shortlist'
    | '/skill-gap'
    | '/talent-pool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AtsScoreRoute: typeof AtsScoreRoute
  BulkScreeningRoute: typeof BulkScreeningRoute
  CareerCoachRoute: typeof CareerCoachRoute
  CareerPredictionRoute: typeof CareerPredictionRoute
  CareerRoadmapRoute: typeof CareerRoadmapRoute
  CompareCandidatesRoute: typeof CompareCandidatesRoute
  HiringAnalyticsRoute: typeof HiringAnalyticsRoute
  InterviewPrepRoute: typeof InterviewPrepRoute
  JdMatchingRoute: typeof JdMatchingRoute
  JobMatchesRoute: typeof JobMatchesRoute
  LearningRoute: typeof LearningRoute
  MockInterviewRoute: typeof MockInterviewRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  ReportsRoute: typeof ReportsRoute
  ResumeAnalyzerRoute: typeof ResumeAnalyzerRoute
  ResumeLibraryRoute: typeof ResumeLibraryRoute
  ResumeRewriterRoute: typeof ResumeRewriterRoute
  SavedJobsRoute: typeof SavedJobsRoute
  SchedulerRoute: typeof SchedulerRoute
  SettingsRoute: typeof SettingsRoute
  ShortlistRoute: typeof ShortlistRoute
  SkillGapRoute: typeof SkillGapRoute
  TalentPoolRoute: typeof TalentPoolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/talent-pool': {
      id: '/talent-pool'
      path: '/talent-pool'
      fullPath: '/talent-pool'
      preLoaderRoute: typeof TalentPoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skill-gap': {
      id: '/skill-gap'
      path: '/skill-gap'
      fullPath: '/skill-gap'
      preLoaderRoute: typeof SkillGapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shortlist': {
      id: '/shortlist'
      path: '/shortlist'
      fullPath: '/shortlist'
      preLoaderRoute: typeof ShortlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scheduler': {
      id: '/scheduler'
      path: '/scheduler'
      fullPath: '/scheduler'
      preLoaderRoute: typeof SchedulerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved-jobs': {
      id: '/saved-jobs'
      path: '/saved-jobs'
      fullPath: '/saved-jobs'
      preLoaderRoute: typeof SavedJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume-rewriter': {
      id: '/resume-rewriter'
      path: '/resume-rewriter'
      fullPath: '/resume-rewriter'
      preLoaderRoute: typeof ResumeRewriterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume-library': {
      id: '/resume-library'
      path: '/resume-library'
      fullPath: '/resume-library'
      preLoaderRoute: typeof ResumeLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume-analyzer': {
      id: '/resume-analyzer'
      path: '/resume-analyzer'
      fullPath: '/resume-analyzer'
      preLoaderRoute: typeof ResumeAnalyzerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mock-interview': {
      id: '/mock-interview'
      path: '/mock-interview'
      fullPath: '/mock-interview'
      preLoaderRoute: typeof MockInterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning': {
      id: '/learning'
      path: '/learning'
      fullPath: '/learning'
      preLoaderRoute: typeof LearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job-matches': {
      id: '/job-matches'
      path: '/job-matches'
      fullPath: '/job-matches'
      preLoaderRoute: typeof JobMatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jd-matching': {
      id: '/jd-matching'
      path: '/jd-matching'
      fullPath: '/jd-matching'
      preLoaderRoute: typeof JdMatchingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview-prep': {
      id: '/interview-prep'
      path: '/interview-prep'
      fullPath: '/interview-prep'
      preLoaderRoute: typeof InterviewPrepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hiring-analytics': {
      id: '/hiring-analytics'
      path: '/hiring-analytics'
      fullPath: '/hiring-analytics'
      preLoaderRoute: typeof HiringAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare-candidates': {
      id: '/compare-candidates'
      path: '/compare-candidates'
      fullPath: '/compare-candidates'
      preLoaderRoute: typeof CompareCandidatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career-roadmap': {
      id: '/career-roadmap'
      path: '/career-roadmap'
      fullPath: '/career-roadmap'
      preLoaderRoute: typeof CareerRoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career-prediction': {
      id: '/career-prediction'
      path: '/career-prediction'
      fullPath: '/career-prediction'
      preLoaderRoute: typeof CareerPredictionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career-coach': {
      id: '/career-coach'
      path: '/career-coach'
      fullPath: '/career-coach'
      preLoaderRoute: typeof CareerCoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulk-screening': {
      id: '/bulk-screening'
      path: '/bulk-screening'
      fullPath: '/bulk-screening'
      preLoaderRoute: typeof BulkScreeningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ats-score': {
      id: '/ats-score'
      path: '/ats-score'
      fullPath: '/ats-score'
      preLoaderRoute: typeof AtsScoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  AtsScoreRoute: AtsScoreRoute,
  BulkScreeningRoute: BulkScreeningRoute,
  CareerCoachRoute: CareerCoachRoute,
  CareerPredictionRoute: CareerPredictionRoute,
  CareerRoadmapRoute: CareerRoadmapRoute,
  CompareCandidatesRoute: CompareCandidatesRoute,
  HiringAnalyticsRoute: HiringAnalyticsRoute,
  InterviewPrepRoute: InterviewPrepRoute,
  JdMatchingRoute: JdMatchingRoute,
  JobMatchesRoute: JobMatchesRoute,
  LearningRoute: LearningRoute,
  MockInterviewRoute: MockInterviewRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  ReportsRoute: ReportsRoute,
  ResumeAnalyzerRoute: ResumeAnalyzerRoute,
  ResumeLibraryRoute: ResumeLibraryRoute,
  ResumeRewriterRoute: ResumeRewriterRoute,
  SavedJobsRoute: SavedJobsRoute,
  SchedulerRoute: SchedulerRoute,
  SettingsRoute: SettingsRoute,
  ShortlistRoute: ShortlistRoute,
  SkillGapRoute: SkillGapRoute,
  TalentPoolRoute: TalentPoolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
